import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import { Container } from '@chakra-ui/react';

import { Footer, Providers } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const raleway = Raleway({
  subsets: ['latin'],
  display: 'swap',
});

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: Readonly<RootLayoutProps>) => (
  <html lang='en' className={raleway.className}>
    <body>
      <Providers>
        <Container>
          {children}

          <Footer />
        </Container>
      </Providers>
    </body>
  </html>
);

export default RootLayout;
