import type { Metadata } from 'next';

import { Providers } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: Readonly<RootLayoutProps>) => (
  <html lang='en'>
    <body>
      <Providers>{children}</Providers>
    </body>
  </html>
);

export default RootLayout;
