import type { Metadata } from 'next';
import { Container } from '@chakra-ui/react';

import { Footer, Header, Providers } from '@/components';

import { fonts } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fontClassNames = Object.values(fonts)
  .map(font => font.className)
  .join(' ');

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = ({ children }: Readonly<RootLayoutProps>) => (
  <html lang='en' className={fontClassNames}>
    <body>
      <Providers>
        <Container gap='36'>
          <Header />

          {children}

          <Footer />
        </Container>
      </Providers>
    </body>
  </html>
);

export default RootLayout;
